FROM serversideup/php:7.4-fpm-nginx

WORKDIR /var/www/html

ENV SSL_MODE off

COPY . .

RUN composer install --no-dev  --optimize-autoloader --prefer-dist --ignore-platform-reqs

RUN php artisan cache:clear

RUN php artisan optimize

RUN php artisan route:cache

RUN php artisan config:cache

RUN php artisan view:cache

RUN php artisan config:clear

RUN chown -R application:application .
# Fix session
RUN chmod -Rf 777 /var/www/html/storage
