version: "3.5"

services:
  ignicao-digital:
   build: .
   container_name: ignicao-digital
   ports:
    - "8000:8000"
   restart: always

   volumes:
    - .:/app/ignicao-digital
    - vendor-ignicao-digital:/app/ignicao-digital/vendor
   networks:
    - conection-netowork
   depends_on:
    - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ignicao
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - conection-netowork


networks:
  conection-netowork:
   name: conection-netowork
   driver: bridge

volumes:
  vendor-ignicao-digital:
    name: vendor-ignicao-digital

  mysqldata:
