FROM serversideup/php:7.4-fpm-nginx

WORKDIR /var/www/html

ENV SSL_MODE off

COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html/storage
RUN chmod -R 777 /var/www/html/storage

# Ensure the correct ownership and permissions for the public directory
RUN chown -R www-data:www-data /var/www/html/public
RUN chmod -R 777 /var/www/html/public

RUN composer install --no-dev  --optimize-autoloader --prefer-dist --ignore-platform-reqs

# Ensure the correct ownership and permissions for the storage directory


RUN php artisan cache:clear

RUN php artisan optimize

RUN php artisan route:cache

RUN php artisan config:cache

RUN php artisan view:cache

RUN php artisan config:clear


